## Machine Learning vs. Deep Learning

Machine learning algorithms are better for structured data

* Random forest
* Gradient boost
* Naive Bayes
* Nearest neighbour
* Support vector machine

Deep learing algorithms are better fir unstructured data, as images, words.

* Neural Networks
* Fully connected neural network
* Convolutional neural network
* Recurrent neural network
* Transformer

Depending how you represent your problem, many algorithms can be used for both


## Bibliography

Trending Research, State of Art, Datasets, Methods and More

[https://paperswithcode.com/](https://paperswithcode.com/)

PyTorch Course Book (PyTorch for Deep Learning in 2023 Zero to Mastery)

[https://www.learnpytorch.io/](https://www.learnpytorch.io/)

Course code, projects and slides

[https://github.com/mrdbourke/pytorch-deep-learning](https://github.com/mrdbourke/pytorch-deep-learning)

Official Website

[https://pytorch.org/](https://pytorch.org/)

# Fundamentals

!nvidia-smi mostrará a GPU que acelerará a execução

In [ ]:
# GPU attributes

!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


## Introduction to Tensors

Creating tensors

In [ ]:
# Scalar

scalar = torch.tensor(7)
print(scalar)

print("Number of Dimensions:", scalar.ndim)

# Tensor as a Python int

print("Scalar as an int:", scalar.item())

tensor(7)
Number of Dimensions: 0
Scalar as an int: 7


In [ ]:
# Vector

vector = torch.tensor([1,7])
print(vector)
print("Number of Dimensions:", vector.ndim)
print("Shape of the tensor:", vector.shape)

tensor([1, 7])
Number of Dimensions: 1
Shape of the tensor: torch.Size([2])


In [ ]:
# Matrix

MATRIX = torch.tensor([[1, 3],[5, 7]])
print(MATRIX)
print("Index at position 0:", MATRIX[0])

tensor([[1, 3],
        [5, 7]])
Index at position 0: tensor([1, 3])


In [ ]:
# Tensor

TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
print(TENSOR)
print("Number of Dimensions:", TENSOR.ndim)
print("Shape of the Tensor:", TENSOR.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Number of Dimensions: 3
Shape of the Tensor: torch.Size([1, 3, 3])


## Random Tensors

1. Start with random numbers
2. Look at Data
3. Update random numbers
4. Look at Data
5. Update random numbers

In [ ]:
# Create a random tensor of size(3,4)

random_tensor = torch.rand(3,4)
print(random_tensor)
print("Number of dimensions:", random_tensor.ndim)
random_tensor2 = torch.rand(2,2,2,2)
print(random_tensor2)
print("Number of dimensions:", random_tensor2.ndim)

tensor([[0.0898, 0.0810, 0.0996, 0.3792],
        [0.2927, 0.2511, 0.6392, 0.2674],
        [0.8970, 0.5887, 0.8343, 0.0362]])
Number of dimensions: 2
tensor([[[[0.1940, 0.7962],
          [0.9821, 0.9852]],

         [[0.7883, 0.4789],
          [0.8178, 0.4980]]],


        [[[0.8179, 0.9288],
          [0.9452, 0.0324]],

         [[0.5544, 0.9867],
          [0.5955, 0.2358]]]])
Number of dimensions: 4


In [ ]:
# Create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size= (3,224,224)) #height, width, colour channel
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([3, 224, 224]))

## Tensors with Zeros and Ones

In [ ]:
zeros = torch.zeros(3,4)
print(zeros)
ones = torch.ones(3,4)
print(ones)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [ ]:
zeros.dtype, ones.dtype

(torch.float32, torch.float32)

## Range of Tensors and Tensors-like

Tensors-like gets the shape of another tensor and completes with another value

In [ ]:
# Range of Tensors

zero_to_nine = torch.arange(0,10)
print(zero_to_nine)
zero_to_twenty_step = torch.arange(0, 20, 2)
print(zero_to_twenty_step)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])


In [ ]:
# Creating tensor like

ten_zeros = torch.zeros_like(input= zero_to_nine)
print(ten_zeros)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


## Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:

1. Tensor not right datatype
2. Tensors not right shape
3. Tensors not on the right device

If a Tensor lays in a device and other Tensor lays in another device, making calculations with these 2 Tensors returns an error

In [ ]:
# Creating a tensor with specific dtype

float_16_tensor = torch.tensor([3, 6, 9], dtype= torch.float16)
print(float_16_tensor, float_16_tensor.dtype)

tensor([3., 6., 9.], dtype=torch.float16) torch.float16


In [ ]:
float_32_tensor = torch.tensor([3,6,9],
                               dtype = None, # What dtype is the tensor
                               device = None, # What device is your tensor on (e.g "cuda", "gpu", "cpu")
                               requires_grad= False) # Whether or not to track grdients with this tensor operations
print(float_32_tensor)

tensor([3, 6, 9])


In [ ]:
int_tensor = float_16_tensor.type(torch.int)
print(int_tensor, int_tensor.dtype)

tensor([3, 6, 9], dtype=torch.int32) torch.int32


## Information from tensors

In [ ]:
some_tensor = torch.rand(3,4)
print(f"Tensor dtype: {some_tensor.dtype}\nTensor shape: {some_tensor.shape} \nTensor device: {some_tensor.device}")

Tensor dtype: torch.float32
Tensor shape: torch.Size([3, 4]) 
Tensor device: cpu


## Manipulating Tensors (Tensors Operations)

Tensor operations include:

1. Addtion
2. Subtraction
3. Multiplication (element-wise)
4. Division
5. Matrix Multiplication

In [ ]:
# Create the tensors

tensor1 = torch.tensor([1,2,3])

# Operations
print(f"Addiction: tensor + 10 = {tensor1 + 10} \nMultiplication: tensor * 10 = {tensor1 * 10} \nSubtraction: tensor - 10 = {tensor1 - 10} \nDivision: tensor / 5 = {tensor1 / 5}")

Addiction: tensor + 10 = tensor([11, 12, 13]) 
Multiplication: tensor * 10 = tensor([10, 20, 30]) 
Subtraction: tensor - 10 = tensor([-9, -8, -7]) 
Division: tensor / 5 = tensor([0.2000, 0.4000, 0.6000])


In [ ]:
# PyTorch in-built functions

print(torch.mul(tensor1, 10))
print(torch.add(tensor1, 5))

tensor([10, 20, 30])
tensor([6, 7, 8])


## Matrix Multiplication

In [ ]:
# Matrix Multiplication

tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([[1],[2],[3]])

print(f"Tensor1: {tensor1}, Tensor2:{tensor2}, Mattrix Multiplication: {torch.matmul(tensor1, tensor2)}")

Tensor1: tensor([1, 2, 3]), Tensor2:tensor([[1],
        [2],
        [3]]), Mattrix Multiplication: tensor([14])


In [ ]:
# Transpose

tensor_A = torch.rand(3,2)
print(f"Original matrix: {tensor_A}")
print(f"Transposed matrix: {tensor_A.T}")
print(tensor_A.shape,tensor_A.T.shape)

Original matrix: tensor([[0.5640, 0.9022],
        [0.4062, 0.8355],
        [0.2290, 0.8610]])
Transposed matrix: tensor([[0.5640, 0.4062, 0.2290],
        [0.9022, 0.8355, 0.8610]])
torch.Size([3, 2]) torch.Size([2, 3])


## Tensor Aggregation (Min, Max, Mean, Sum, etc)

Mean() function can't work in tensors with long dtypes. It only can be used with floating point or complex dtypes

In [ ]:
x = torch.arange(0,100,10)
print(x.min(), x.max(), x.sum(), x.type(torch.float32).mean())

tensor(0) tensor(90) tensor(450) tensor(45.)


## Finding the positional Min and Max

In [ ]:
print(x.argmin(), x.argmax())
print(x[0], x[x.argmax()])

tensor(0) tensor(9)
tensor(0) tensor(90)


## Reshaping, Viewing, Stacking, Squeezing and Unsqueezong Tensors

1. Reshaping - Reshapes an input tensor to a defined shape
2. View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
3. Stacking - Combine multiple tensors on top of each other (vstack) or side by side (hstack)
4. Squeezing - Remove all '1' dimensions from a tensor
5. Unsqueeze - Add a 1 dimension to a target tensor
6. Permute - Return a view of the input with dimencions permuted (swapped) in a certain way

In [ ]:
y = torch.arange(1., 10.)
y, y.shape

# Add an extra dimension

y_reshaped = y.reshape(1, 9)
print(y_reshaped, y.reshape(9,1))

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]) tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])


In [ ]:
# Change the view

y_view = y.view(1,9)
print(y_view, y_view.shape)

# Changing y_view changes y (because a view of a tensor shares the same memory)

y_view[:,0] = 5
print(y, y_view)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])
tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]) tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])


In [ ]:
# Stacking tensors on top

y_stacked = torch.stack([y,y,y,y], dim= 0) #vstack
y_stacked1 = torch.stack([y,y,y,y], dim= 1) #hstack
print(y_stacked, y_stacked1)

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]]) tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])


In [ ]:
# Squeezing

y_squezeed = y_reshaped.squeeze()
print(y_squezeed, y_reshaped)
tensor1 = torch.rand(2,3)
tensor1_squeezed = tensor1.squeeze()
print(tensor1, tensor1_squeezed)

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]) tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
tensor([[0.3771, 0.4516, 0.2860],
        [0.9273, 0.0822, 0.6966]]) tensor([[0.3771, 0.4516, 0.2860],
        [0.9273, 0.0822, 0.6966]])


In [ ]:
# Unsqueezing

y_unsqueezed = y_reshaped.unsqueeze(dim = 0)
print(y_reshaped.shape, y_unsqueezed.shape)
y_unsqueezed = y_reshaped.unsqueeze(dim = 1)
print(y_reshaped.shape, y_unsqueezed.shape)
y_unsqueezed = y_reshaped.unsqueeze(dim = 2)
print(y_reshaped.shape, y_unsqueezed.shape)
y_unsqueezed = y_reshaped.unsqueeze(dim = -1)
print(y_reshaped.shape, y_unsqueezed.shape)
y_unsqueezed = y_reshaped.unsqueeze(dim = -2)
print(y_reshaped.shape, y_unsqueezed.shape)

torch.Size([1, 9]) torch.Size([1, 1, 9])
torch.Size([1, 9]) torch.Size([1, 1, 9])
torch.Size([1, 9]) torch.Size([1, 9, 1])
torch.Size([1, 9]) torch.Size([1, 9, 1])
torch.Size([1, 9]) torch.Size([1, 1, 9])


In [ ]:
# Permuting

# Change the order of the dimensions

y = torch.rand(1,2,3)
print(y.shape, y.permute(2,0,1).shape)

torch.Size([1, 2, 3]) torch.Size([3, 1, 2])


## Indexing (Selectiong data from tensors)

In [ ]:
# Index

x = torch.arange(1,10).reshape(1,3,3)
print(x, x.shape)

# Index on the middle bracket (dim=1)
print(x[0][0])

# Index on the most inner bracket (last dimension)

print(x[0][0][0])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) torch.Size([1, 3, 3])
tensor([1, 2, 3])
tensor(1)


In [ ]:
# Using ":" to select the target dimension

x[:,0]

tensor([[1, 2, 3]])

## PyTorch Tensors with Numpy

* Data in Numpy to PyTorch Tensor: torch.from_numpy(ndarray)
* PyTorch Tensor to Numpy: torch.Tensor.numpy()

Numpy default dtype is float64, so when a numpy array is converted to pytorch tensor, the tensor dtype will be float64.

In [ ]:
# Numpy array to tensor

array = np.arange(1,8)
tensor = torch.from_numpy(array)
array.dtype, tensor.dtype

(dtype('int64'), torch.int64)

In [ ]:
# Converting numpy to pytorch or vice-versa creates a memory allocation,
# so when the array or the tensor is changed there wont be any change in the other variable

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor.dtype, numpy_tensor.dtype

(torch.float32, dtype('float32'))

## Reproducibility (trying to take random out of randim)

To reduce the randomness in neural networks an PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness

In [ ]:
# Set the random seed
RANDOM_SEED = 1
torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)



tensor([[0.7576, 0.2793, 0.4031, 0.7347],
        [0.0293, 0.7999, 0.3971, 0.7544],
        [0.5695, 0.4388, 0.6387, 0.5247]])
tensor([[0.7576, 0.2793, 0.4031, 0.7347],
        [0.0293, 0.7999, 0.3971, 0.7544],
        [0.5695, 0.4388, 0.6387, 0.5247]])


## PyTorch objects on the GPUs

1. Easiest - Use Google Colab
2. Use your own GPU
3. Use Cloud computing - GCP, AWS, Azure

For 2,3, PyTorch + GPU (CUDA) takes a bit of setting up

In [ ]:
# Check for GPU access with PyTorch

torch.cuda.is_available()

False

In [ ]:
# Setup device agnostic code

device = "cuda" if torch.cuda.is_available() else "cpu"

In [ ]:
# Count number os devices

torch.cuda.device_count()

0

## Puttong tensor (and models) on the GPU

In [ ]:
# Create a tensor
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor, tensor.device)

#Move tensor to GPU (if available)

tensor_on_gpu = tensor.to(device)
print(tensor_on_gpu)

# Moving tensor to CPU
# If tensor is on GPU, can't transform it to Numpy
tensor_to_cpu = tensor_on_gpu.cpu()
print(tensor_to_cpu.device)

tensor([1, 2, 3]) cpu
tensor([1, 2, 3])
cpu
