#### Tensors

Tensor is a geometric object that describes the relationship between vectors, scalars, and other tensors in a multi-dimensional space.

A tensor can be defined by its rank, which refers to the number of indices required to specify each of its components, and its shape, which specifies the number of components in each dimension

#### Creating Tensors

In [2]:
import tensorflow as tf

In [3]:
string = tf.Variable('This is a string', tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

#### Rank/Degree of Tensors

3 tensor was created aboved with rank 0 (1D).

Tensors with higher degrees/rank is shown below

In [5]:
rank1_tensor = tf.Variable(['Test'], tf.string) ##This is an array
rank2_tensor = tf.Variable([['test','ok'],['test','yes']], tf.string)

To determine the rank of a tensor, use the following method

In [6]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

#### Shape of Tensors

Amount of elements that exist in each dimension. To get the shape of a tensor, use the shape attribute

In [7]:
rank2_tensor.shape

TensorShape([2, 2])

Changing Shape

In [12]:
tensor1 = tf.ones([1, 2, 3]) # tf.ones() creates a shape ([1,2,3]) full of ones
print(tensor1)
tensor2 = tf.reshape(tensor1, [2,3,1]) # reshape existing data to shape [2,3,1]
print(tensor2)
tensor3 = tf.reshape(tensor2, [3, -1]) # -1 tells the tensor to calculate the size of the dimension in that place
print(tensor3)

# the number of elements in the reshaped tensor MUST match the number in the original

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


#### Types of Tensors

* Variable
* Constant
* Placeholder
* Sparse Tensor

With the exception of Variable all of these tensors are immuttable

#### Evaluating Tensors

Evaluate a tensor in order other words means get its value

In [16]:
tensor2.numpy()

array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]], dtype=float32)